server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system_logs
    journal:
      path: /var/log/journal
      max_age: 12h
      labels:
        job: journalctl
    relabel_configs:
      - source_labels: ["__journal__systemd_unit"]
        target_label: "unit"

  - job_name: docker_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container_name"

      - target_label: "job"
        replacement: "docker"

    pipeline_stages:
      - docker: {}
      - output:
          source: log

  - job_name: nginx_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log
          
  - job_name: vps_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: vps
          __path__: /var/log/*.log
